import type { Metadata } from "next";
// import "../styles/all.css";
import "../styles/globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Header />
      <main className="min-h-screen bg-light text-dark py-12">
        {children}
      </main>
      </body>
    </html>
  );
}
