import type { Metadata } from 'next';
// import "../styles/all.css";
import '../styles/globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <main className='min-h-screen bg-light px-6 py-12 text-dark'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
